
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: npm install
- script:  run unittest-ci


- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: JUnit
    testResultsFiles: '**\TEST-Result.xml'
    testRunTitle: 'Mocha Test Run'
