# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: azure-pipelines-steps.yml

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: azure-pipelines-steps.yml 

  - job: macOS
    pool:
      vmImage: 'xcode9-macos10.13'
    steps:
      - template: azure-pipelines-steps.yml 

  # - job: Release
  #   pool:
  #     vmImage: 'ubuntu-16.04'
  #   dependsOn:
  #     - Linux
  #     - Windows
  #     - macOS
  #   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  #   steps:
  # NPM INSTALL
  # NPM VERSION
  # RELEASE NOTE ?
  # PREPUBLISH
  # vsce package
  # vsce publish -p <token>