
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: Npm Install

- script: npm run vscode:prepublish
  displayName: Typescript Compile

- script: npm run unittest-ci
  displayName: Run unit tests

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: JUnit
    testResultsFiles: '**\TEST-Result.xml'
    testRunTitle: 'Mocha Test Run'
